version: "3"
services:

   db:
     image: postgres:9.6
     restart: always
     environment:
       POSTGRES_PASSWORD: ${POSTG_PAS}
       POSTGRES_DB: ${POSTG_DB}
     ports:
       - ${PORTS}
     volumes:
       - ./postgres-data:/bitnami/postgresql/data
